# Generated by Django 4.0.6 on 2022-07-04 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField()),
                ('year_guarantee', models.PositiveSmallIntegerField()),
                ('availability', models.BooleanField()),
                ('published', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
