# Generated by Django 4.0.6 on 2022-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Unknown name', max_length=20),
        ),
    ]
